# Config yaml for 'kal-calibrate vanilla'

filter: 1
smoother: 3
algorithm: "NUMBA"
sigma_f: 0.2  
sigma_n: 0.1
step_control: 0.5
model_column: "J0, J1, J2, J3"
vis_column: "DATA"
weight_column: "WEIGHT"
out_file: "gains.npy"
which_gains: "SMOOTHER"